server:
  port: 8280

spring:
  cloud:
    function:
      definition: messageConsumer;messagesConsumer;genericMessageConsumer;genericMessagesConsumer;messageProducerAutomated;genericMessagesConsumerLongRebalanced;genericMessagesConsumerLongCompleted
    stream:
      kafka:
        binder:
          brokers: localhost
          min-partition-count: 1
          auto-create-topics: true
          consumer-properties:
            value.deserializer: com.mmaracic.kafka_long_process_demo.MessageDeserializer
            max.poll.interval.ms: 1000
            max.poll.records: 10
        bindings:
          genericMessageConsumer-in-0:
            consumer:
              ack-mode: manual
          genericMessagesConsumer-in-0:
            consumer:
              ack-mode: manual
          genericMessagesConsumerLongRebalanced-in-0:
            consumer:
              ack-mode: manual
          genericMessagesConsumerLongCompleted-in-0:
            consumer:
              ack-mode: manual
      bindings:
        messageConsumer-in-0:
          destination: test-topic
          group: group-1
          consumer:
            auto-startup: false
            batch-mode: false
            concurrency: 1
            reset-offsets: true
        messagesConsumer-in-0:
          destination: test-topic
          group: group-2
          consumer:
            auto-startup: false
            batch-mode: true
            concurrency: 1
            reset-offsets: true
        genericMessageConsumer-in-0:
          destination: test-topic
          group: group-3
          consumer:
            auto-startup: false
            batch-mode: false
            concurrency: 1
            reset-offsets: true
        genericMessagesConsumer-in-0:
          destination: test-topic
          group: group-4
          consumer:
            auto-startup: false
            batch-mode: true
            concurrency: 1
            reset-offsets: true
        genericMessagesConsumerLongRebalanced-in-0:
          destination: test-topic
          group: group-5
          consumer:
            auto-startup: true
            batch-mode: true
            concurrency: 1
            reset-offsets: true
        genericMessagesConsumerLongCompleted-in-0:
          destination: test-topic
          group: group-6
          consumer:
            auto-startup: false
            batch-mode: true
            concurrency: 1
            reset-offsets: true
        messageProducerAutomated-out-0:
          destination: test-topic

logging:
  level:
    org:
      springframework:
        kafka: info